<a href="https://colab.research.google.com/github/EnesBAKAR/yapay-zeka/blob/main/numpy_1244.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np



* 1) (10,15,30,45,60) değerlerine sahip numpy dizisi oluştur

In [9]:
np.arange(10,60)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

* 2) 5-15 arasındaki sayılarla bir dizi oluştur

* 4) 10 elemanlı sıfırlardan oluşan bir dizi oluşturun


In [12]:
result=np.zeros(10)
result


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.arange(5,15)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

* 3) 50-100 arasında 5 er 5 er bir dizi oluştur

* 5 ) 10 elemanlı birlerden  oluşan bir dizi oluşturun

In [14]:
result=np.ones(10)
result

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

* 6) (0-100) arasında eşit aralıklı 5 sayı üretin

In [15]:
result=np.linspace(0,100,5)
result

array([  0.,  25.,  50.,  75., 100.])

* 7) (10-30) arasında rastgele 5 tam sayı üretin

In [16]:
result=np.random.randint(10,30,5)
result

array([14, 20, 24, 21, 27])

* 8) [-1 ile 1] arasında 10 adet sayı üretin

In [17]:
result=np.random.randn(10)
result

array([ 0.03720884, -0.72005341, -0.2433801 , -0.57355552, -0.27771749,
        0.33243324,  1.1263982 , -1.09822691,  0.2706954 ,  3.03123786])

* 9) (3x5)  boyutlarında (10-50) arasında rastgele bir matriks oluşturunuz

In [18]:
result=np.random.randint(10,50,15).reshape(3,5)
result

array([[23, 20, 16, 16, 46],
       [21, 20, 36, 28, 10],
       [26, 43, 18, 48, 40]])

* 10) Üretilen matrisin  satır ve sütun sayıları toplamlarını hesaplayınız ?

In [20]:
matris=np.random.randint(10,50,15).reshape(3,5)
rowYTotal=matris.sum(axis=1)
columnXTotal=matris.sum(axis=0)
print(rowYTotal)
print(columnXTotal)

[153  95 126]
[98 77 92 40 67]


* 11) Üretilen Matrisin en  büyük değerinin indeksi kaçtır=

In [21]:
result=np.random.randint(10,50,15).reshape(3,5)
print(result)
print(result.argmax())

[[34 44 33 23 13]
 [36 42 13 28 24]
 [11 23 47 35 25]]
12


* 12) üretilen matrisin en büyük,en küçük ve ortalaması nedir?

In [22]:
result=np.random.randint(10,50,15).reshape(3,5)
print(result)
print(result.max())
print(result.min())
print(result.mean())

[[35 20 43 29 19]
 [10 43 39 21 40]
 [41 34 17 37 48]]
48
10
31.733333333333334


* 13) (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz

In [23]:
arr=np.arange(10,20)
arr[:3]

array([10, 11, 12])

* 14) üretilen dizinin elemanlarını tersten yazdırın

In [24]:
result=np.random.randint(10,50,15).reshape(3,5)
print(result)
print(result[::-1])

[[12 46 36 20 28]
 [45 23 21 27 41]
 [47 34 15 21 27]]
[[47 34 15 21 27]
 [45 23 21 27 41]
 [12 46 36 20 28]]


* 15) üretilen matrisin ilk sayısını seçiniz

In [25]:
result=np.random.randint(10,50,15).reshape(3,5)
print(result)
print(result[0,0])

[[37 10 24 47 22]
 [46 24 17 16 48]
 [40 33 35 30 30]]
37


* 16) üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir?

In [26]:
result=np.random.randint(10,50,15).reshape(3,5)
print(result)
print(result[1,2])

[[36 23 23 15 25]
 [44 21 38 13 34]
 [16 29 28 15 40]]
38


* 17) üretilen matrisin tüm satırlardaki ilk elemanı seçiniz

In [27]:
result=np.random.randint(10,50,15).reshape(3,5)
print(result)
print(result[:,0])

[[10 32 41 46 28]
 [45 36 35 15 42]
 [12 49 19 42 38]]
[10 45 12]


* 18) üretilen matrisin her bir elemanının karesini alınız

In [28]:
result=np.random.randint(10,50,15).reshape(3,5)
print(result)
print(result**2)

[[20 26 19 38 18]
 [42 34 36 42 47]
 [25 48 23 10 45]]
[[ 400  676  361 1444  324]
 [1764 1156 1296 1764 2209]
 [ 625 2304  529  100 2025]]


* 19) üretilen matris elemanlarının hangisi pozitif çift sayıdır?

In [38]:
ciftler=matris[matris %2 == %0]

SyntaxError: invalid syntax (<ipython-input-38-371bfad009b8>, line 1)

In [10]:
np.arange(50,100,5)

array([50, 55, 60, 65, 70, 75, 80, 85, 90, 95])